# Site wide configuration

title: Delapan Piksel
locale: en_US
description: "Sebuah website yang berisi opini dari Jaka Santana"
logo: site-logo.png
search: true
url: http://localhost:4000
url: https://delapanpx.com
authors: Jaka Santana

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess", "robots.txt"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE.md", "README.md", "vendor"]


# Site owner
owner:
  name: Jaka Santana
  avatar: cicaheum.jpg
  email: jaka@delapanpx.com
  disqus-shortname:
  twitter: delapanpx
  facebook: delapanpiksel
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
